# Generated by Django 5.2.5 on 2025-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="industry",
            name="name",
            field=models.CharField(
                choices=[
                    ("category 1", "category 1"),
                    ("category 2", "category 2"),
                    ("category 3", "category 3"),
                    ("category 4", "category 4"),
                    ("category 5", "category 5"),
                    ("category 6", "category 6"),
                    ("category 7", "category 7"),
                    ("category 8", "category 8"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="name",
            field=models.CharField(
                choices=[
                    ("Autonomous Republic of Crimea", "Autonomous Republic of Crimea"),
                    ("Lviv Oblast", "Lviv Oblast"),
                    ("Ivano-Frankivsk Oblast", "Ivano-Frankivsk Oblast"),
                    ("Odesa Oblast", "Odesa Oblast"),
                    ("Rivne Oblast", "Rivne Oblast"),
                    ("Ternopil Oblast", "Ternopil Oblast"),
                    ("Sumy Oblast", "Sumy Oblast"),
                    ("Kyiv Oblast", "Kyiv Oblast"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
