# Generated by Django 5.2.5 on 2025-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projectstatus_savedstartup_startupproject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectstatus",
            name="status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Funded", "Funded")],
                max_length=150,
                unique=True,
            ),
        ),
    ]
