# Generated by Django 5.2.5 on 2025-08-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projectrevision"),
        ("projects", "0005_alter_startupproject_status_delete_projectstatus"),
    ]

    operations = []
