# t = tuple()
# print(type(t), t)
# t = tuple([1,2,3,4])
# print(type(t), t)
# t = ()
# print(type(t), t)
# t = (1) #<class 'int'> 1
# print(type(t), t)
# t = (1,) 
# print(type(t), t)
# t = (1,1,2,3,45, [1,2,3]) 
# print(type(t), t)
# print(t[1])
# # t[1] = 20 #ypeError: 'tuple' object does not support item assignment
# t[-1][2] = 30
# print(t)
print([method for method in dir(tuple) if not method.startswith("_")])

# print(t.count(1))
# print(t.index(45))

r = range(10)
print(list(r).__sizeof__())
print(tuple(r).__sizeof__())
r = range(100)
print(list(r).__sizeof__())
print(tuple(r).__sizeof__())
r = range(1000)
print(list(r).__sizeof__())
print(tuple(r).__sizeof__())
r = range(10000)
print(list(r).__sizeof__())
print(tuple(r).__sizeof__())