# Generated by Django 5.2.5 on 2025-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("category 1", "category 1"),
                            ("category 2", "category 2"),
                            ("category 3", "category 3"),
                            ("category 4", "category 4"),
                            ("category 5", "category 5"),
                            ("category 6", "category 6"),
                            ("category 7", "category 7"),
                            ("category 8", "category 8"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(blank=True, max_length=150)),
                ("website", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            (
                                "Autonomous Republic of Crimea",
                                "Autonomous Republic of Crimea",
                            ),
                            ("Lviv Oblast", "Lviv Oblast"),
                            ("Ivano-Frankivsk Oblast", "Ivano-Frankivsk Oblast"),
                            ("Odesa Oblast", "Odesa Oblast"),
                            ("Rivne Oblast", "Rivne Oblast"),
                            ("Ternopil Oblast", "Ternopil Oblast"),
                            ("Sumy Oblast", "Sumy Oblast"),
                            ("Kyiv Oblast", "Kyiv Oblast"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StartupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("views_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ViewedStartup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
    ]
