# Generated by Django 5.2.5 on 2025-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        ("projects", "0004_remove_startupproject_investor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="saved_projects",
            field=models.ManyToManyField(
                through="projects.SavedProject", to="projects.startupproject"
            ),
        ),
    ]
