# Generated by Django 5.2.5 on 2025-08-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_industry_name_alter_location_name"),
        ("profiles", "0002_investorprofile_saved_projects"),
    ]

    operations = []
