# Generated by Django 5.2.5 on 2025-08-28 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_viewedstartup"),
        ("profiles", "0003_merge_20250827_1226"),
    ]

    operations = []
