# Generated by Django 5.2.5 on 2025-08-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[("INVESTOR", "Investor"), ("STARTUP", "Startup")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
