# Generated by Django 5.2.5 on 2025-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userrole_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[("investor", "Investor"), ("startup", "Startup")],
                max_length=15,
                unique=True,
            ),
        ),
    ]
