# Generated by Django 5.2.5 on 2025-08-30 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="investorprofile",
            name="saved_projects",
            field=models.ManyToManyField(
                through="projects.SavedProject", to="projects.startupproject"
            ),
        ),
        migrations.AddField(
            model_name="investorprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="startupprofile",
            name="industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="startups",
                to="profiles.industry",
            ),
        ),
        migrations.AddField(
            model_name="startupprofile",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="startup_locations",
                to="profiles.location",
            ),
        ),
        migrations.AddField(
            model_name="startupprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="startups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="viewedstartup",
            name="startup",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="profiles.startupprofile",
            ),
        ),
        migrations.AddField(
            model_name="viewedstartup",
            name="user",
            field=models.ForeignKey(
                limit_choices_to={"role__role": "investor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="viewed_startups",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="viewedstartup",
            constraint=models.UniqueConstraint(
                fields=("user", "startup"), name="unique_investor_startup_view"
            ),
        ),
    ]
