# Generated by Django 5.2.5 on 2025-09-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_alter_investorprofile_user"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investorprofile",
            name="saved_projects",
            field=models.ManyToManyField(
                related_name="saved_entries",
                through="projects.SavedProject",
                to="projects.startupproject",
            ),
        ),
    ]
