# Generated by Django 5.2.5 on 2025-08-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_remove_startupproject_investor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="startupproject",
            name="status",
            field=models.CharField(
                choices=[("PENDING", "Pending"), ("FUNDED", "Funded")],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ProjectStatus",
        ),
    ]
